#!/bin/sh

# disable Lion new window animation
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool NO
# disable Spaces animation
defaults write com.apple.dock workspaces-swoosh-animation-off -bool YES
# disable Mail.app animations
defaults write com.apple.Mail DisableReplyAnimations -bool YES
# disable Mountain Lion scroll animation
defaults write -g NSScrollAnimationEnabled -bool NO
# Fix iTunes arrows
defaults write com.apple.iTunes show-store-arrow-links -bool YES
defaults write com.apple.iTunes show-store-link-arrows -bool YES
defaults write com.apple.iTunes invertStoreLinks -bool YES

# Most of the settings below have been stolen from https://github.com/mathiasbynens/dotfiles/blob/master/.osx

# Show the ~/Library folder
chflags nohidden ~/Library
# Make ⌘ + F focus the search input in iTunes
defaults write com.apple.iTunes NSUserKeyEquivalents -dict-add "Target Search Field" "@F"
# Add a context menu item for showing the Web Inspector in web views
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
# Enable AirDrop over Ethernet and on unsupported Macs running Lion
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true
# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true
# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false
# Use current directory as default search scope in Finder
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# Show Path bar in Finder
defaults write com.apple.finder ShowPathbar -bool true
# Show Status bar in Finder
defaults write com.apple.finder ShowStatusBar -bool true
# Enable subpixel font rendering on non-Apple LCDs
defaults write NSGlobalDomain AppleFontSmoothing -int 2
# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
# Enable text selection in quick view
defaults write com.apple.finder QLEnableTextSelection -bool TRUE
# disable hibernate, because sometimes the stupid machine won't wake up from sleep
# sudo pmset -a hibernatemode 0

# Show remaining battery time; hide percentage
defaults write com.apple.menuextra.battery ShowPercent -string "NO"
defaults write com.apple.menuextra.battery ShowTime -string "YES"

# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# Desktop: enable snap-to-grid for desktop icons
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist


