### COMMON OPTIONS ###
setopt AUTO_CD # '$ foo' means '$ cd foo' if 'foo' is not a command
setopt AUTO_PUSHD # 'cd' is now cooler

### KEYBINDINGS ###
bindkey -e
bindkey '^u' backward-kill-line # in zsh ^u kills the whole line
# make alt-<arrow> move between words
bindkey '^[[1;9D' backward-word
bindkey '^[[1;9C' forward-word

### LINE EDIT BINDINGS ###
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\ee' edit-command-line
bindkey '\eq' push-line-or-edit
# complete in the middle of some text ignoring the suffix
bindkey '^i' expand-or-complete-prefix

### PROMPT ###
# prompt shamelessly stolen from http://github.com/skanev/SHELLFILES/blob/master/zsh/config
# sans the vcprompt, which doesn't help me much with subversion
autoload -U colors
colors
setopt prompt_subst
if [ $(id -u `whoami`) -eq 0 ]; then
	ROOT_PROMPT='#'
else
	ROOT_PROMPT=''
fi
PROMPT='%{$fg_bold[green]%}%{$ROOT_PROMPT%}%{$reset_color%}→ '
RPROMPT='%{$fg_bold[green]%}%~%{$fg_bold[white]%}:%{$fg_bold[blue]%}%m %{$fg_bold[red]%}$(vcprompt)%{$reset_color%}'

### COMPLETION ###
autoload compinit
compinit

# enable cache for slow commands
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
# show menu when completing PIDs for kill
zstyle ':completion:*:*:kill:*' menu yes select

### HISTORY ###
HISTFILE=~/.zsh_history # if unset, the history is not saved
HISTSIZE=1000 # history items kept internally
SAVEHIST=1000 # history items saved

setopt HIST_IGNORE_DUPS # ignore duplication command history list
setopt SHARE_HISTORY # share command history data
setopt HIST_IGNORE_SPACE # don't keep in history commands, which start with space
setopt APPEND_HISTORY # write history only when closing
setopt EXTENDED_HISTORY # add more info
setopt HIST_FCNTL_LOCK # smarter locking

### MISC ###
autoload url-quote-magic
zle -N self-insert url-quote-magic # auto-quote special chars in URLs
WORDCHARS=`echo $WORDCHARS | sed 's/[\/=#_&;-]//g'` # add more word separators
